name: movie_assignment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.12.30
  riverpod: ^2.5.0
  http: ^1.2.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  provider: ^6.1.1
  shared_preferences: ^2.0.10
  url_launcher: ^6.0.9
  youtube_player_flutter: ^9.0.0
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

